# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  topics: terraform,terraform-module,registry
  private: true
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: false
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  
teams:
  - name: cloud-all-members
    permission: pull
  - name: squad-automatizacion
    permission: maintain

branches:
  - name: prod
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
      enforce_admins: true
